[disable_mobs]
	alligator_removed = false
	bass_removed = false
	bear_removed = false
	bird_removed = false
	boar_removed = false
	butterfly_removed = false
	catfish_removed = false
	deer_removed = false
	dragonfly_removed = false
	duck_removed = false
	elephant_removed = false
	firefly_removed = false
	forest_fox_removed = false
	forest_rabbit_removed = false
	giraffe_removed = false
	hippo_removed = false
	lion_removed = false
	lizard_removed = false
	rhino_removed = false
	snail_removed = false
	snake_removed = false
	tortoise_removed = false
	vulture_removed = false
	zebra_removed = false
